add gradio UI for sd2_mega
bentoml/diffusers-examples pull request #1
Opened 2023-04-11 01:34 UTC by larme

2023-04-14 07:52 UTC, aarnphm requested changes
First pass

2023-04-14 07:52 UTC, aarnphm commented on requirements.txt
> +gradio==3.20.0
Is there any reason for locking it to 3.20.0? does gradio usually introduce breaking change?

2023-04-14 07:52 UTC, aarnphm commented on sd2_mega/bentofile.yaml
> +    - gradio==3.20.0
For the python packages, lets just use `requirements_txt: ./requirements.txt` instead since there will only be one source of truth for dependencies

2023-04-14 07:52 UTC, aarnphm commented on sd2_mega/bentofile.yaml
> +    - gradio==3.20.0
For bentoml packages ,since we are using Image just do `bentoml[io-image]`.

2023-04-14 07:52 UTC, aarnphm commented on sd2_mega/service_with_gradio.py
> +@svc.api(input=img2img_input_spec, output=Image())
```suggestion
@svc.api(input=Multipart(img=Image(), data=JSON()), output=Image())
```

2023-04-14 07:52 UTC, aarnphm commented on sd2_mega/service_with_gradio.py
> +from bentoml.io import Image, JSON, Multipart
```suggestion
```

No need to do this since `bentoml.io` is already lazily imported,

s/Image/bentoml.io.Image/g

s/JSON/bentoml.io.JSON/g

s/Multipart/bentoml.io.Multipart/g

2023-04-14 07:52 UTC, aarnphm commented on sd2_mega/service_with_gradio.py
> +from PIL import Image
put import to top of file?

2023-04-14 07:52 UTC, aarnphm commented on sd2_mega/service_with_gradio.py
> +"""
Can we make this into a css file, it seems like from a quick search `gr.Blocks(css="/path/to/file.css")` does work?

2023-04-14 07:52 UTC, aarnphm commented on sd2_mega/service_with_gradio.py
> +        f"""
```suggestion
        """
```

2023-04-14 07:52 UTC, aarnphm commented on sd2_mega/service_with_gradio.py
> +            <div class="diffusion-spave-div">
seems like this class is not referenced anywhere in the CSS?

2023-04-14 07:52 UTC, aarnphm commented on requirements.txt
> +gradio==3.20.0
Also triton only works on Linux, and it doesn't work on darwin, maybe we can also add a restriction `python_platform=="Linux"` to triton?

2023-04-17 10:20 UTC, aarnphm commented on sd2_mega/service_with_gradio.py
> +from PIL import Image
chat with @larme, to add comments about this style

2023-04-17 10:21 UTC, larme commented on sd2_mega/service_with_gradio.py
> +"""
let's make this css string prettier

2023-04-17 21:12 UTC, larme commented on requirements.txt
> +gradio==3.20.0
locking gradio to 3.20.0 until https://github.com/gradio-app/gradio/issues/3472 is solved

2023-04-17 21:12 UTC, larme commented on sd2_mega/bentofile.yaml
> +    - gradio==3.20.0
done

2023-04-17 21:15 UTC, larme commented on sd2_mega/service_with_gradio.py
> +from PIL import Image
We are having 2 parts of codes in the same file. The first part is the ordinary BentoML api endpoint service part. The second part is gradio webUI part. I haven't find a good way to separate this to 2 files now, so we put them in one file. To separate these 2 parts, we put imports needed by gradio behind the first part

2023-04-17 21:20 UTC, larme commented on requirements.txt
> +gradio==3.20.0
Triton for mac need some building, let's omit it now and only require triton for linux. This will only disable some optimization without losing functionality

2023-04-17 21:22 UTC, larme commented
@aarnphm please review again

2023-04-18 03:05 UTC, aarnphm commented on sd2_mega/README.md
> +```
```suggestion
```bash
```

2023-04-18 03:06 UTC, aarnphm approved these changes
LGTM

2023-04-18 03:07 UTC, merged